<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="axis_dome_fixed" params="prefix parent topic stand_height:=0.062 *origin">
    <link name="${prefix}_base_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://axis_description/meshes/axis_dome.stl" scale="1 1 1" />
        </geometry>
        <material name="axis_white">
          <color rgba="0.8 0.8 0.8 1.0" />
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <!-- Cylinder for the main body of the camera -->
        <geometry>
          <cylinder radius="0.09" length="0.09" />
        </geometry>
        <origin xyz="0 0 ${stand_height + 0.09/2}" rpy="0 0 0" />
      </collision>
      <collision>
        <!-- Sphere collider for the dome itself -->
        <geometry>
          <sphere radius="0.067" />
        </geometry>
        <origin xyz="0 0 ${stand_height + 0.09}" />
      </collision>
      <collision>
        <!-- Box collider for the metal stand the camera sits on -->
        <geometry>
          <box size="0.04 0.08 ${stand_height}" />
        </geometry>
        <origin xyz="0 0 ${stand_height/2}" rpy="0 0 0" />
      </collision>
    </link>
    <joint name="${prefix}_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}_base_link" />
    </joint>

    <link name="${prefix}_camera_link" />
    <joint name="${prefix}_camera_joint" type="fixed">
      <parent link="${prefix}_base_link" />
      <child link="${prefix}_camera_link" />
      <origin xyz="0.047 0 ${stand_height + 0.09 + 0.047}" rpy="0 0.7854 0" />
    </joint>

    <gazebo reference="${prefix}_camera_link">
      <material>Gazebo/Black</material>
      <sensor type="camera" name="${prefix}_dome_camera">
        <update_rate>15</update_rate>
        <camera>
          <horizontal_fov>6.28</horizontal_fov>
          <vertical_fov>1.57</vertical_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.05</near>
            <far>500.0</far>
          </clip>
        </camera>
        <plugin name="${prefix}_camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <cameraName>${prefix}_camera</cameraName>
          <imageTopicName>${topic}</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${prefix}_camera_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>